<a href="https://colab.research.google.com/github/prachijoshi0/BCG-Gen-AI-Project/blob/main/Forage_BCGX_Gen_AI_Data_Extraction_and_Initial_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing the necessary Modules

In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

### Reading the Manually Extracted Dataset from SEC's EDGAR's database
### <a href>https://www.sec.gov/edgar/searchedgar/cik</a>

In [51]:
data = pd.read_csv('/content/Final.csv')

In [52]:
data

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities
0,F21,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0
1,F21,Apple,365817.0,94680.0,351002.0,287912.0,104038.0
2,F21,Tesla,53823.0,-5644.0,62131.0,30548.0,11497.0
3,F22,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0
4,F22,Apple,394328.0,99803.0,352755.0,302083.0,122151.0
5,F22,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0
6,F23,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0
7,F23,Apple,383285.0,96995.0,352583.0,290437.0,110543.0
8,F23,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Calculating Year-by-Year growth rates for Total Revenue and Net Income

In [53]:
data['Revenue Growth (%)'] = data.groupby('Company')['Total Revenue'].pct_change() * 100
data['Net Income Growth (%)'] = data.groupby('Company')['Net Income'].pct_change() * 100

In [54]:
data

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%)
0,F21,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0,NaN,NaN
1,F21,Apple,365817.0,94680.0,351002.0,287912.0,104038.0,NaN,NaN
2,F21,Tesla,53823.0,-5644.0,62131.0,30548.0,11497.0,NaN,NaN
3,F22,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0,17.956071,18.715216
4,F22,Apple,394328.0,99803.0,352755.0,302083.0,122151.0,7.793788,5.410858
5,F22,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0,51.351653,-323.015592
6,F23,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0,6.882030,-0.518299
7,F23,Apple,383285.0,96995.0,352583.0,290437.0,110543.0,-2.800461,-2.813543
8,F23,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0,18.795267,18.964010
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Imputing Null/NaN values that result from pct_change calculations with 0

In [55]:
data.fillna(0, inplace=True)

In [56]:
data

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%)
0,F21,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0,0.000000,0.000000
1,F21,Apple,365817.0,94680.0,351002.0,287912.0,104038.0,0.000000,0.000000
2,F21,Tesla,53823.0,-5644.0,62131.0,30548.0,11497.0,0.000000,0.000000
3,F22,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0,17.956071,18.715216
4,F22,Apple,394328.0,99803.0,352755.0,302083.0,122151.0,7.793788,5.410858
5,F22,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0,51.351653,-323.015592
6,F23,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0,6.882030,-0.518299
7,F23,Apple,383285.0,96995.0,352583.0,290437.0,110543.0,-2.800461,-2.813543
8,F23,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0,18.795267,18.964010
9,0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
10,0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

### Calculating Year-by-Year growth rates for Total Assets, Total Liabilities and Cash flow from Operations Activities

In [57]:
data['Assets Growth (%)'] = data.groupby('Company')['Total Assets'].pct_change() * 100
data['Liabilities Growth (%)'] = data.groupby('Company')['Total Liabilities'].pct_change() * 100
data['Cash Flow from Operations Growth(%)'] = data.groupby('Company')['Cash Flow from Operating Activities'].pct_change() * 100

In [58]:
data

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Cash Flow from Operations Growth(%)
0,F21,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0,0.000000,0.000000,NaN,NaN,NaN
1,F21,Apple,365817.0,94680.0,351002.0,287912.0,104038.0,0.000000,0.000000,NaN,NaN,NaN
2,F21,Tesla,53823.0,-5644.0,62131.0,30548.0,11497.0,0.000000,0.000000,NaN,NaN,NaN
3,F22,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0,17.956071,18.715216,9.305858,3.392756,16.021631
4,F22,Apple,394328.0,99803.0,352755.0,302083.0,122151.0,7.793788,5.410858,0.499427,4.921990,17.409985
5,F22,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0,51.351653,-323.015592,32.523217,19.287678,28.068192
6,F23,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0,6.882030,-0.518299,12.919636,3.759493,-1.631942
7,F23,Apple,383285.0,96995.0,352583.0,290437.0,110543.0,-2.800461,-2.813543,-0.048759,-3.855232,-9.502992
8,F23,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0,18.795267,18.964010,29.488207,18.026894,-9.970117
9,0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN
10,0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN

In [59]:
data.fillna(0, inplace=True)

In [ ]:
data

,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Company,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Cash Flow from Operations Growth(%)
0,2023,211915,72361,411976,205753,87582,Microsoft,0.000000,0.000000,0.000000,0.000000,0.000000
1,2022,198270,72738,364840,198298,89035,Microsoft,-6.438902,0.520999,-11.441443,-3.623276,1.659017
2,2021,168088,61271,333779,191791,76740,Microsoft,-15.222676,-15.764800,-8.513595,-3.281425,-13.809176
3,2023,96773,14974,106618,43009,13256,Tesla,0.000000,0.000000,0.000000,0.000000,0.000000
4,2022,81462,12556,82338,36440,14724,Tesla,-15.821562,-16.147990,-22.772890,-15.273547,11.074231
5,2021,53821,5519,62131,30548,11497,Tesla,-33.931158,-56.044919,-24.541524,-16.169045,-21.916599
6,2023,383285,96995,352583,290437,110543,Apple,0.000000,0.000000,0.000000,0.000000,0.000000
7,2022,394328,99803,352755,302083,122151,Apple,2.881146,2.894995,0.048783,4.009820,10.500891
8,2021,365817,94680,351002,287912,104038,Apple,-7.230275,-5.133112,-0.496945,-4.691095,-14.828368

In [60]:
data.to_csv('final_data_report.csv')

In [61]:
mean_growth = data.groupby('Company')[['Revenue Growth (%)', 'Net Income Growth (%)', 'Assets Growth (%)', 'Liabilities Growth (%)', 'Cash Flow from Operations Growth(%)']].mean().reset_index()

In [62]:
print('Year-By-Year Average Growth Rates(%) :-')
print('             OR')
print("Overall Growth/Fall rate for Apple, Microsoft and Tesla from Fiscal Year 2021 - 2023")
mean_growth

Year-By-Year Average Growth Rates(%) :-
             OR
Overall Growth/Fall rate for Apple, Microsoft and Tesla from Fiscal Year 2021 - 2023

,Company,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Cash Flow from Operations Growth(%)
0,0,0.000000,0.000000,0.000000,0.000000,0.000000
1,Apple,1.664442,0.865772,0.150223,0.355586,2.635664
2,Microsoft,8.279367,6.065639,7.408498,2.384083,4.796563
3,Tesla,23.382306,-101.350527,20.670475,12.438191,6.032692

In [63]:
# prompt: Using dataframe summary: barplot

import altair as alt
alt.Chart(mean_growth).mark_bar().encode(
    alt.X('Company:N', title='Company'),
    alt.Y('Revenue Growth (%):Q', title='Revenue Growth (%)'),
    color='Company:N',
).properties(width=alt.Step(80)).interactive()

alt.Chart(...)

In [64]:
mean_growth.to_csv('Summary_final_report.csv')


#This task involves Manual extraction of Financial Statements of Microsoft, Apple and Tesla for the fiscal year 2021, 2022 and 2023 respectively.

# I completed my this task by following these steps :-

#1. Organizing  Data:
Ensure that dataset is structured properly with columns for Year, Company,	Total Revenue,	Net Income, Total Assets,	Total Liabilities,	Cash Flow from Operating Activities
#2. Calculate Year-over-Year Percentage Change:
Use the pct_change() function to calculate the percentage change for each metric year-over-year within each company group.
#3. Handle Missing Values:
The pct_change() function will result in NaN for the first year of each company since there is no previous year to compare. Decide how you want to handle these NaN values (e.g., removing them or replacing them with 0 or another value).
#4. Calculate the Mean of Percentage Changes:
After calculating the percentage changes, find the mean of these changes across all years for each company.